
# @! monitors setup --------------------------------------------------
monitor=DP-1,1920x1080@60Hz,0x550,1
monitor=HDMI-A-1,1920x1080@60Hz,1920x0,1,transform,3

# @! workspaces setup ------------------------------------------------
workspace=1, monitor:DP-1
workspace=2, monitor:DP-1
workspace=3, monitor:DP-1
workspace=4, monitor:DP-1
workspace=5, monitor:DP-1
workspace=6, monitor:DP-1
workspace=7, monitor:DP-1
workspace=8, monitor:HDMI-A-1
workspace=9, monitor:HDMI-A-1
workspace=10, monitor:HDMI-A-1

# @! layout setup ----------------------------------------------------
general {
    layout = master
}

scrolling {
    column_width = 0.334
}

workspace = m[DP-1], layout:master, layoutopt:orientation:left
workspace = 8, layout:scrolling, layoutopt:orientation:bottom, layoutopt:direction:down
workspace = 9, layout:scrolling, layoutopt:orientation:bottom, layoutopt:direction:down
workspace = 10, layout:master, layoutopt:orientation:bottom
