# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = match:class foot, opacity 0.88 override 0.88 override
windowrule = match:class org.gnome.Nautilus, opacity 0.88 override 0.88 override
windowrule = match:class org.gnome.Settings, opacity 0.88 override 0.88 override

windowrule = match:title ^(Mozilla Firefox)(.*)$, opacity 0.85 override 0.85 override
windowrule = match:title ^(Waterfox)(.*)$, opacity 0.85 override 0.85 override
windowrule = match:class code, opacity 0.89 override 0.89 override
windowrule = match:class ^(.*[Zz]ed.*)$, opacity 0.89 override 0.89 override

windowrule = match:class org.gnome.Loupe, fullscreen on


